waypoints:
    - point:
        x: -15.799
        y: -30.600
        z: 0
    - point:
        x: -4.700
        y: -30.142
        z: 0
    - point:
        x: 4.420
        y: -30.514
        z: 0
    - point:
        x: 15.912
        y: -30.702
        z: 0
