waypoints:
- point: {x: 5.24883, y: 0.299301, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 20.2006, y: 1.69447, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 33.5002, y: 2.08246, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 47.3383, y: 2.15765, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 55.9006, y: 1.6036, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 60.305, y: -4.48562, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 65.3182, y: -15.6003, z: 0.0, vel: 1.0, rad: 0.5, stop: false}
- point: {x: 70.8621, y: -15.9114, z: 0.0, vel: 0.5, rad: 0.5, stop: false}
- point: {x: 75.3498, y: -15.8108, z: 0.0, vel: 0.5, rad: 0.5, stop: false}
- point: {x: 78.316778, y: -16.085512, z: 0.0, vel: 0.5, rad: 0.5, stop: false}
- point: {x: 79.735711, y: -17.30174, z: 0.0, vel: 0.5, rad: 0.5, stop: false}
- point: {x: 81.007222, y: -18.573251, z: 0.0, vel: 0.5, rad: 0.5, stop: false}
- point: {x: 82.8513, y: -19.436, z: 0.0, vel: 0.5, rad: 0.5, stop: false}
- point: {x: 87.7516, y: -19.8763, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 87.898391, y: -10.591395, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 87.55817, y: -2.142565, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 86.537506, y: 2.847348, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 69.5118, y: 0.541712, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 62.208, y: -5.61149, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 58.7626, y: -8.91244, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 55.7271, y: -10.4897, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: 47.8533, y: -10.6475, z: 0.0, vel: 1, rad: 0.5, stop: false}
- point: {x: 45.7889, y: -11.658, z: 0.0, vel: 0.5, rad: 0.4, stop: false}
- point: {x: 42.9629, y: -12.1382, z: 0.0, vel: 0.5, rad: 0.5, stop: false}
- point: {x: 34.9496, y: -12.2287, z: 0.0, vel: 0.6, rad: 0.5, stop: false}
- point: {x: 34.5935, y: -15.2689, z: 0.0, vel: 0.6, rad: 0.5, stop: false}
- point: {x: 33.6834, y: -17.8155, z: 0.0, vel: 0.6, rad: 0.5, stop: false}
- point: {x: 32.7517, y: -19.126, z: 0.0, vel: 0.6, rad: 0.5, stop: false}
- point: {x: 26.267135, y: -18.924958, z: 0.0, vel: 1, rad: 0.8, stop: false}
- point: {x: 22.563169, y: -18.795965, z: 0.0, vel: 0.5, rad: 0.5, stop: false}
- point: {x: 20.2475, y: -18.8274, z: 0.0, vel: 0.5, rad: 0.5, stop: false}
- point: {x: 17.596, y: -18.9779, z: 0.0, vel: 0.5, rad: 0.5, stop: false}
- point: {x: 13.9365, y: -19.0423, z: 0.0, vel: 0.5, rad: 0.5, stop: false}
- point: {x: 6.8739, y: -18.5676, z: 0.0, vel: 1, rad: 0.4, stop: false}
- point: {x: 4.66837, y: -25.1465, z: 0.0, vel: 1, rad: 0.6, stop: false}
- point: {x: 0.810068, y: -26.158161, z: 0.0, vel: 1, rad: 0.8, stop: false}
- point: {x: -4.47588, y: -26.158161, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: -11.258451, y: -25.839731, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: -17.276789, y: -25.776045, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: -23.0342, y: -25.5307, z: 0.0, vel: 1, rad: 0.5, stop: true}
- point: {x: -35.6457, y: -29.3766, z: 0, vel: 1, rad: 0.8, stop: false}
- point: {x: -38.5361, y: -30.6251, z: 0.0, vel: 1, rad: 0.8, stop: false}
finish_pose:
  header: {seq: 0, stamp: 1663386810.6123521, frame_id: map}
  pose:
    position: {x: -43.5257, y: -31.2852, z: 0}
    orientation: {x: 0, y: 0, z: 0.999988, w: 0.00484186}
